# Generated by Django 4.2.7 on 2025-06-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('skills', models.TextField(help_text='Comma-separated list of skills')),
                ('projects', models.TextField(help_text='Comma-separated list of projects or JSON')),
                ('contacts', models.TextField(help_text='Contact information, e.g. email, phone, links')),
            ],
        ),
    ]
